"""add owner_id to contracts

Revision ID: a5e56b380e25
Revises: e9b8da64c4bb
Create Date: 2026-09-14 06:27:57.632152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e56b380e25'
down_revision: Union[str, None] = 'e9b8da64c4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'owner_id')
    # ### end Alembic commands ###
