"""add contract versioning fields

Revision ID: c7c8797eeb09
Revises: d4543ffb3ac0
Create Date: 2026-09-11 21:58:18.527603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c8797eeb09'
down_revision: Union[str, None] = 'd4543ffb3ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('contracts', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('parent_contract_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'contracts', ['parent_contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precedent_clauses', sa.Column('text_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, text)", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_precedent_clauses_text_search', 'precedent_clauses', ['text_search'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
